# -*- coding: utf-8 -*-
"""codigos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ixMOHryuSWHM_X51wMLcff9XDNMdNacs
"""



codigos = {
    "histograma": '''
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

plt.hist(df_limpio["temperatura_tenido"], bins=10)

plt.title("Distribución de la temperatura de teñido")
plt.xlabel("Temperatura de teñido (°C)")
plt.ylabel("Frecuencia")

plt.grid(axis="y", linestyle="--", linewidth=0.5)

plt.show()
''',
    "barras": '''
#Grafico de barras

plt.figure(figsize=(10, 6))
ax= sns.countplot(x='apto_consumo', data=df, palette='viridis')

# Añadir las etiquetas de valor sobre cada barra
for container in ax.containers:
    ax.bar_label(container)

plt.title('Distribución de Aptitud del Agua para Consumo')
plt.xlabel('Categoría (Apto/No Apto)')
plt.ylabel('Frecuencia de Muestras')
plt.show()
''',
    "lineas": '''
import matplotlib.pyplot as plt

df_limpio=df
plt.figure(figsize=(12, 5))

plt.plot(df_limpio["ph_bano"], marker="o", markersize=3)

plt.title("ph_bano por observación")
plt.xlabel("Número de observación")
plt.ylabel("ph_bano")

plt.show()
''',
    "2variablescategoricas": '''
# Gráfico de barras apiladas
import pandas as pd
import matplotlib.pyplot as plt

tabla = pd.crosstab(df["Turno"], df["Resultado"])

tabla.plot(kind="bar", figsize=(12, 6))

plt.title("Resultado de producción según turno")
plt.xlabel("Turno")
plt.ylabel("Cantidad de lotes")
plt.xticks(rotation=90)
plt.grid(axis="y", linestyle="--", linewidth=0.5)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
plt.tight_layout()
plt.show()
''',
    "boxplot": '''
plt.figure(figsize=(10, 6))
sns.boxplot(x='fuente', y='coliformes', data=df, palette='viridis')
plt.title('Distribución de Coliformes por Fuente de Agua')
plt.xlabel('Fuente de Agua')
plt.ylabel('Coliformes')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
''',
    "scatter": '''
# Gráfico Scatter
plt.figure(figsize=(10, 6))
sns.scatterplot(x='ph', y='coliformes', data=df, hue='fuente', palette='viridis', s=100, alpha=0.7)
plt.title('Relación entre Coliformes y pH del Agua')
plt.xlabel('pH del Agua')
plt.ylabel('Coliformes')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()
''',
    "cargar":'''
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

o

cargar doc
df = pd.read_csv('horneado_pan.csv')
print("Las 10 primeras filas son: ")
print(df.head(10))
''',
    "shape":'''
df.shape
df.info()
''',
    "descripcion":'''
df.describe()
''',
    "columnas":'''
#descriptiva por columna(ESTADÍSTICOS Lote_ID)
df["Lote_ID"].describe()
''',
    "resumen.estadistico":'''
print("\n--- Resumen Estadístico ---")
print(df.describe())
''',
    "dtypes":'''
# Tipos de datos incorrectos - Informacion General
df.dtypes,df.info()
''',
    "nulos":'''
#Identificar nulos
print("\n--- Identificar nulos ---")
print(df.isnull().sum())
''',
    "rangos":'''
# Detección de rangos físicos (pH no puede ser negativo)
fuera_rango = df[df['ph'] < 0]
print(f"PALO HACIA ABAJO DERECHA Y N MINUSCULA Registros con pH fuera de rango: {len(fuera_rango)}\n")
# MOSTRAR LOS DATOS FUERA DEL RANGO
print(df.loc[fuera_rango.index])

 O

REMPLZAR VALORES
ph_corregido = df["ph"].replace(to_replace=-1, value=0)
print("\n--- Verificar el reemplazo ---")
print(ph_corregido)

o

REMPLZAR VALORES
# Se agregan comillas a los textos y se aplica correctamente sobre la columna
df["Tipo_Pan"] = df["Tipo_Pan"].replace(to_replace="MASAMADRE", value="MASA MADRE")

print("--- Verificar el reemplazo ---")
print(df["Tipo_Pan"])
''',
    "valores":'''
print("\n--- Valores únicos ---")
print(df.nunique())

O

print("\nValores únicos en 'fuente':")
print(df['fuente'].unique())

print("\nValores únicos en 'apto_consumo':")
print(df['apto_consumo'].unique())

O

valores_unicos_sin_nulos = df['apto_consumo'].dropna().unique()
print(f"Valores únicos de 'apto_consumo' (sin nulos): {valores_unicos_sin_nulos}")
''',
    "mmm":'''
#Mediana... evitar el sesgo de valores extremos
df['turbidez_NTU'] = df['turbidez_NTU'].fillna(df['turbidez_NTU'].median())

# Cloro: Media para mantener el equilibrio estadístico de la concentración química.
df['cloro_mg_L'] = df['cloro_mg_L'].fillna(df['cloro_mg_L'].mean())

#Coliformes: Moda la frecuencia de contaminación más común en los registros.
df['coliformes'] = df['coliformes'].fillna(df['coliformes'].mode()[0])

print(df['turbidez_NTU'])
print(df['cloro_mg_L'])
print(df['coliformes'])
''',
    "estandarizacion":'''
# Estandarización de cadenas para eliminar errores de digitación
for col in ['Tipo_Pan', 'Turno', 'Operario']:
    df[col] = df[col].astype(str).str.split().str.join(' ').str.upper()

# Verificar cambios después de la estandarización
print("Datos después de limpieza:")
print(df.head())
''',
    "contar valores":'''
# Cuántos de cada producto
print(df["producto"].value_counts())
''',
    "guardar":'''
# 3. Guardar dataset limpio en condicion_tela
df_limpio_condicion = df.copy()
 #Guardar en excel
df_limpio_condicion.to_excel("tela_tenido_limpio_condicion.xlsx", index=False)
import pandas as pd
df = pd.read_excel("tela_tenido_s_sucio.xlsx")
''',

}

def info(nombre=None):
    if nombre is None:
        print("Códigos disponibles:")
        for codigo in codigos:
            print("-", codigo)
    elif nombre.lower() in codigos:
        print(codigos[nombre.lower()])
    else:
        print("No existe ese código.")

info()
