# -*- coding: utf-8 -*-
"""codigos.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pSPuhcQIOZLi_RgDakGzU51o_3Wqi7Ot
"""

codigos = {
    "histograma": '''
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

plt.hist(df_limpio["temperatura_tenido"], bins=10)

plt.title("Distribución de la temperatura de teñido")
plt.xlabel("Temperatura de teñido (°C)")
plt.ylabel("Frecuencia")

plt.grid(axis="y", linestyle="--", linewidth=0.5)

plt.show()
''',

    "barras": '''
#Grafico de barras

plt.figure(figsize=(10, 6))
ax= sns.countplot(x='apto_consumo', data=df, palette='viridis')

# Añadir las etiquetas de valor sobre cada barra
for container in ax.containers:
    ax.bar_label(container)

plt.title('Distribución de Aptitud del Agua para Consumo')
plt.xlabel('Categoría (Apto/No Apto)')
plt.ylabel('Frecuencia de Muestras')
plt.show()
''',
    "Lineas": '''
import matplotlib.pyplot as plt

df_limpio=df
plt.figure(figsize=(12, 5))

plt.plot(df_limpio["ph_bano"], marker="o", markersize=3)

plt.title("ph_bano por observación")
plt.xlabel("Número de observación")
plt.ylabel("ph_bano")

plt.show()
''',
    "boxplot": '''
plt.figure(figsize=(10, 6))
sns.boxplot(x='fuente', y='coliformes', data=df, palette='viridis')
plt.title('Distribución de Coliformes por Fuente de Agua')
plt.xlabel('Fuente de Agua')
plt.ylabel('Coliformes')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
''',

    "Scatter": '''
# Gráfico Scatter
plt.figure(figsize=(10, 6))
sns.scatterplot(x='ph', y='coliformes', data=df, hue='fuente', palette='viridis', s=100, alpha=0.7)
plt.title('Relación entre Coliformes y pH del Agua')
plt.xlabel('pH del Agua')
plt.ylabel('Coliformes')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()
'''
}

def ayuda(nombre=None):
    if nombre is None:
        print("Códigos disponibles:")
        for codigo in codigos:
            print("-", codigo)
    elif nombre.lower() in codigos:
        print(codigos[nombre.lower()])
    else:
        print("No existe ese código.")

ayuda()